### ISSUE TITLE
Missing Features, Application to run Executables.

### ISSUE THREAD

**Issue by Abhinav1217** [GabMus/mLauncher#1]
Hi, Nice application. I have been using [DFC](https://github.com/Abhinav1217/desktop-file-creator) for many years, nice to have a refresher UI.  There are two things this need.
1.  Option for Executable command should be there before Application Path .
   I used mlauncher to create a desktop file for a wine application. Upon clicking the icon, it showed error message.  Then Looking in the desktop file code, I found that `EXEC=` contains only the path of the executable, not the executable command. I prefixed it with `WINE` and it worked fine. 
2. Missing options to add keywords and other stuffs.  They are usefull in filtering and searching. 

I would suggest you to take a look at DFC ( Not my code, I imported to my account because Google code is closing )  .  UI is dated  but it has all the features I have seen in any .desktop file.  Your refreshed UI and DFC's features will make a killing application.

**Comment by GabMus** [comment]
Thanks for the comment, users' support is really appreciated. About your first point, I'm not quite sure what your problem is. Maybe it's a little unclear, but the "Executable" entry contains exactly what will appear in after Exec= in the .desktop file. The file chooser button on the right is just there if you want to execute a file instead of using a command and want to search for it with a file browser.
About the second point, I'm gonna look at DFC and try to add some more features.
Again, thanks for the feedback!

**Comment by GabMus** [comment]
I'm don't think your first point can be considered a "problem" by itself, probably it's just a misunderstaning. I'm closing this, if you feel like it you can open a new issue.

**Comment by Abhinav1217** [comment]
Perhaps I should elaborate with examples. Please bear with me. 

In mLauncher, You provide the path of executable ( Which is **usually** a script with shebang in Linux ) and it set it to `EXEC=/path/to/script` .  This is correct most of the times but not always correct. 

Where this method fails. 
_1. This will fail when the script does not contain any shebang._ 
In this case it will fail.  Because shell is not provided.  For Example correct solution would be `EXEC= <python> /path/to/python/script`  Then it would work correctly.

_2. When the executable is not a script but a binary which needs a runtime environment._
I didn't give this a full try but I created a desktop icon for one of my java application. Icon didn't launch the application. Whereas the icon which I had been using ( Created with DFC ) works fine. 

_3. Wine Application ( Same thing as above, Binary which needs a distinct runtime )_
Like I said in the Issue, When I created Icon of a wine application, Error was thrown.  mLauncher generated file contained `EXEC=/path/to/game.exe`  All I needed to do was edit it to `EXEC=`_`wine`_`/path/to/game.exe` and it works correctly. 

What it is missing is an option to add command(wine, python etc) along with the script path, Which is required many times. 

According to Official Standard for desktop entries, EXEC line, should contain a proper commandline entrie to execute, 
http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html

Another thing accordant to official standard, all the entry values must be within double quotes. 
Currently you do not have double quotes in any of the value `NAME=Application Name` must be `NAME="Application Name"` .

**Comment by Abhinav1217** [comment]
Simple words,   Awesome interface, great usability, but output is not in accordance of Official Standards, Hence does not cover all scenarios. I got myself in a scenario where It didn't work.  I am not a great Python programmer but happy to extend all help I can to make this more awesome.

**Comment by GabMus** [comment]
I'm perfectly aware of this, but I still think it's a misunderstanding of how the program works. I made a video to explain that I considered this scenario when I made mLauncher, in fact you can just plain write in the "Executable" text field, without the need to select a file with the file picker. I did in the video below, but just because I didn't want to enter the jar path manually, but I could have done it. Whatever gets in the Executable field gets in the desktop file as is. You could also write cmatrix there and it would work (I actually did for most of my tests).

https://drive.google.com/file/d/0B_7SP7Pp5whPQ1ZmR2hJbDF4bXc/view?usp=sharing

If you still aren't convinced, it's clear that we're having a communication issue. In this case please contact me privately on Google+ or Hangouts (here's my G+ profile: https://plus.google.com/u/0/+GabrieleMusco/posts) or on Telegram if you prefer (my username is @gabmus).
